### ISSUE TITLE
按照你的说明设置了API权限，但是部署到一半就报错。

### ISSUE THREAD

**Issue by samling-jackyjyo** [Ray-D-Song/web-archive#16]
![image](https://github.com/user-attachments/assets/ebec499d-5fec-43e1-9884-c8cd5ab11079)

**Comment by Ray-D-Song** [comment]
检查一下 R2 有没有写入权限，有的话那大概是偶发性的网络错误，你有试着手动 re-run github actions 吗？

**Comment by samling-jackyjyo** [comment]
我完全按照你的设置配置的，也re-run过了，也是报错
![image](https://github.com/user-attachments/assets/7bc08ab8-8841-4c05-a2c4-5d619bc3ea34)

**Comment by Ray-D-Song** [comment]
抱歉，我知道原因了，R2 是需要在 Cloudflare 面板上手动开通后才可以使用的功能，在部署之前我已经开通过所以才没有发现。  
麻烦你开通后再试一下。  

Sorry, I know the reason now. R2 is a feature that needs to be manually enabled on the Cloudflare panel before it can be used. I had already enabled it before deployment, so I didn't notice.
Please try again after you have activated it.

**Comment by samling-jackyjyo** [comment]
R2存储桶名字有要求吗

**Comment by Ray-D-Song** [comment]
只需要开通 R2 功能就好了，存储桶会在执行 actions 时创建

**Comment by samling-jackyjyo** [comment]
部署成功了，请问如何登录面板呢？

**Comment by Ray-D-Song** [comment]
在 Cloudflare pages 面板中你应该可以看到 web-archive 项目，点击项目部署后的链接就行了。
