### ISSUE TITLE
【功能请求】有可能接入 AI 功能吗？

### ISSUE THREAD

**Issue by kiwiflydream** [Ray-D-Song/web-archive#23]
目前在使用 https://github.com/hoarder-app/hoarder ，最大的亮点就是通过 AI 自动生成 tags，不过其它就比较一般。我看到 Roadmap 中有标签系统的规划，是否考虑自动生成的功能。图片是自动生成的效果。

![CleanShot 01112024--at 12 08 58@2x](https://github.com/user-attachments/assets/53fea939-d985-4864-9784-f1b3a28334ea)

**Comment by dimlau** [comment]
如果对比一些成熟项目（我之前在用 Readeck）的话，
还是补齐基础功能才是优先级更高的工作吧。
比如搜索，高亮划线之类的。

**Comment by Ray-D-Song** [comment]
> 如果对比一些成熟项目（我之前在用 Readeck）的话， 还是补齐基础功能才是优先级更高的工作吧。 比如搜索，高亮划线之类的。

抱歉... 其实本来有切换 list 视图和文件夹内搜索的功能，但是昨天被我合没了😂
现在你sync fork应该就可以看到

**Comment by Ray-D-Song** [comment]
> 目前在使用 https://github.com/hoarder-app/hoarder ，最大的亮点就是通过 AI 自动生成 tags，不过其它就比较一般。我看到 Roadmap 中有标签系统的规划，是否考虑自动生成的功能。图片是自动生成的效果。

我们有做过 Cloudflare worker AI 的 demo，但是效果不是很好。
web-archive的初衷就是基于Cloudflare这个免费的平台做的轻量服务，如果后续 worker AI 的能力满足要求的话会引入。

**Comment by kiwiflydream** [comment]
> > 目前在使用 https://github.com/hoarder-app/hoarder ，最大的亮点就是通过 AI 自动生成 tags，不过其它就比较一般。我看到 Roadmap 中有标签系统的规划，是否考虑自动生成的功能。图片是自动生成的效果。
> 
> 我们有做过 Cloudflare worker AI 的 demo，但是效果不是很好。 web-archive的初衷就是基于Cloudflare这个免费的平台做的轻量服务，如果后续 worker AI 的能力满足要求的话会引入。

嗯，其实不用区分 ai 平台的，只要提供用户设置 URL 与 KEY 的配置就可以了。大部分模型都支持兼容 openai 的 api 请求，包括 Cloudflare worker AI  https://developers.cloudflare.com/workers-ai/configuration/open-ai-compatibility/ 。不过前面说的对，的确有更优先的事需要做，我先关了。
