### ISSUE TITLE
Command Deploy 方式部署存在两个问题

### ISSUE THREAD

**Issue by Tsai002** [Ray-D-Song/web-archive#26]
1. 提示找不到 init.sql，改成 `npx wrangler d1 execute web-archive --remote --file=./src/sql/migrations/0001_init.sql`后成功。
2. 找不到设置`BEARER_TOKEN`的方法，`wrangler.toml`里没有该字段。

**Comment by banzhe** [comment]
这块调整过，文档还没改
初始化数据库现在通过`npx wrangler d1 migrations apply web-archive --remote`
BEARER_TOKEN现在改成存数据库里了，部署后第一次输入的token会作为密码

**Comment by Tsai002** [comment]
@banzhe 谢谢，按照你的新命令已经部署成功了。另外想问下，扩展是适配 Chrome 的对吧？支持 Firefox 吗？

**Comment by banzhe** [comment]
> @banzhe 谢谢，按照你的新命令已经部署成功了。另外想问下，扩展是适配 Chrome 的对吧？支持 Firefox 吗？

目前我只在chrome上测试过

**Comment by Ray-D-Song** [comment]
文档已更新
