### ISSUE TITLE
保存微信公众号时图片由于lazy-load没有完全加载

### ISSUE THREAD

**Issue by wwng2333** [Ray-D-Song/web-archive#29]
如题。
测试链接：https://mp.weixin.qq.com/s/7LxbwWvzcjPRsTcXyHDQlA
保存的图片：
![image](https://github.com/user-attachments/assets/084de585-fceb-49ce-a3c3-7a2a8a438ad4)
正常的情况：
![image](https://github.com/user-attachments/assets/ba8067f8-6ecc-48fc-bf2b-18a74bab75ba)

**Comment by banzhe** [comment]
新加了个配置项Load Deferred Images用于控制是否加载懒加载的图片，默认开启
