### ISSUE TITLE
常见问题 common issue

### ISSUE THREAD

**Issue by Ray-D-Song** [Ray-D-Song/web-archive#31]
Q: R2 部署过程报错
A: R2 功能需要在 Cloudflare 面板手动开启，需要绑定信用卡或 paypal，开通成功后再手动执行 github actions 即可。

Q: 如何更新服务？
A: 使用一键部署会 fork 一份到自己的仓库，点击 sync fork 在代码更新的同时会自动触发部署。
使用命令部署的话需要下载最新代码并再次手动执行命令。

Q: 什么时候上架 chrome 商店？
A: tag 功能开发好后会发布 0.1.0 正式版并上架

Q: 接口访问速度很慢如何优化？
A: 可以尝试开启worker的[Smart Placement](https://developers.cloudflare.com/workers/configuration/smart-placement/)。或者重新创建D1，并指定距离近的 [Data location](https://developers.cloudflare.com/d1/configuration/data-location/)，重新创建的D1只要保证名称为web-archive即可，创建之后需要到Github Action中手动触发一次部署。

---

Q: R2 deployment process error
A: The R2 feature needs to be manually enabled in the Cloudflare panel, and a credit card or PayPal must be linked. After successful activation, you can manually execute GitHub actions.

Q: How to update the service?
A: Using one-click deployment will fork a copy to your own repository. Clicking sync fork will automatically trigger deployment while the code is updated.
If you are using commands to deploy, you need to download the latest code and manually execute the commands again.

Q: When will it be available on the Chrome Store?
A: The tag function will be officially released as version 0.1.0 after development is complete and will be available for download.

Q: How can I optimize slow interface access?

A: You can try enabling [Smart Placement](https://developers.cloudflare.com/workers/configuration/smart-placement/) for the worker, or you can recreate D1 and specify a closer [Data location](https://developers.cloudflare.com/d1/configuration/data-location/). When recreating D1, ensure the name is set to "web-archive." After creation, you’ll need to manually trigger a deployment in GitHub Actions.

**Comment by Hyphen-H** [comment]
太nb了，接收omnivore难民😊而且还能绕过知乎验证，爱了❤️❤️❤️❤️❤️

### 一些小建议 大佬看看就行:)
- 希望可以在通过浏览器插件archive的时候直接新建分类，现在在浏览器插件中只能选中已有分类。
- 目前只能在页面存在且等待浏览器插件提示完成，才能成功Archive. 希望可以直接把链接粘贴到插件Archive / 单击Save Page后可以安全地关闭页面，后台Save
- 希望浏览器插件支持粘贴一些剪切板内容或者是文本（text），因为有时是不需要archive整个页面的，只希望保存部分文本。
- 希望加入高亮、导入导出等等同类软件（readeck, hoarder, obsidian web clipper, omnivore）功能。

### 发现一个Light Theme小bug：

archive Telegraph的一个[页面](https://telegra.ph/2024%E5%B9%B4%E5%A4%A7%E9%80%89%E7%9A%84%E4%B8%80%E4%BA%9B%E6%84%9F%E6%83%B3%E6%88%91%E5%9C%A82016%E5%92%8C20-11-06)时，iframe生成的预览对比度过低。
![image](https://github.com/user-attachments/assets/89a7eaba-85f6-4679-931a-2ead0eeb67bd)

**Comment by Ray-D-Song** [comment]
> 太nb了，接收omnivore难民😊而且还能绕过知乎验证，爱了❤️❤️❤️❤️❤️
> 
> ### 一些小建议 大佬看看就行:)
> * 希望可以在通过浏览器插件archive的时候直接新建分类，现在在浏览器插件中只能选中已有分类。
> * 目前只能在页面存在且等待浏览器插件提示完成，才能成功Archive. 希望可以直接把链接粘贴到插件Archive / 单击Save Page后可以安全地关闭页面，后台Save
> * 希望浏览器插件支持粘贴一些剪切板内容或者是文本（text），因为有时是不需要archive整个页面的，只希望保存部分文本。
> * 希望加入高亮、导入导出等等同类软件（readeck, hoarder, obsidian web clipper, omnivore）功能。
> 
> ### 发现一个Light Theme小bug：
> archive Telegraph的一个[页面](https://telegra.ph/2024%E5%B9%B4%E5%A4%A7%E9%80%89%E7%9A%84%E4%B8%80%E4%BA%9B%E6%84%9F%E6%83%B3%E6%88%91%E5%9C%A82016%E5%92%8C20-11-06)时，iframe生成的预览对比度过低。 ![image](https://private-user-images.githubusercontent.com/103420806/384652248-89a7eaba-85f6-4679-931a-2ead0eeb67bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTMxNTEsIm5iZiI6MTczMTIxMjg1MSwicGF0aCI6Ii8xMDM0MjA4MDYvMzg0NjUyMjQ4LTg5YTdlYWJhLTg1ZjYtNDY3OS05MzFhLTJlYWQwZWViNjdiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwNDI3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2IyNmY3MWJmMDE1OGM5ZWI0OTgzYjI1NDI5YWJlYWE1MjJiNTUyYTYwMDIyMGM1MDk2ZjdkYTVhMTJjYzMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.p2L6iaSZS0hjTq-ZP9_0tc5VrUA3I-DoPsi1ed5fFlY)

感谢，划词高亮已添加到 roadmap 中，近期会考虑实现。
telegraph page 对比度问题和网站切换主题的实现方式相关，暂时没找到解决方案。

**Comment by Ray-D-Song** [comment]
> ### 发现一个Light Theme小bug：
> archive Telegraph的一个[页面](https://telegra.ph/2024%E5%B9%B4%E5%A4%A7%E9%80%89%E7%9A%84%E4%B8%80%E4%BA%9B%E6%84%9F%E6%83%B3%E6%88%91%E5%9C%A82016%E5%92%8C20-11-06)时，iframe生成的预览对比度过低。 ![image](https://private-user-images.githubusercontent.com/103420806/384652248-89a7eaba-85f6-4679-931a-2ead0eeb67bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDQzNDksIm5iZiI6MTczMTI0NDA0OSwicGF0aCI6Ii8xMDM0MjA4MDYvMzg0NjUyMjQ4LTg5YTdlYWJhLTg1ZjYtNDY3OS05MzFhLTJlYWQwZWViNjdiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxMzA3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTQ3N2RlNTU5OWQ4YTc2MmFmMTJiMTQ5NWE5MTlmZjQ0MzczNTE2YTVkZDA2Nzk3YTQ3NDAyOGM3NTRhOTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ro78asSoRcvpMy6BMtBVbAGSdjR0f-DGjJNM1wN0H7U)

对比度问题修复了，请 sync fork 一下。

**Comment by robustmaster** [comment]
目录中设置了可在showcase中展示，但实际访问showcase页面没有看到文章，是空白的。比如这个网址：https://web-archive-9ta.pages.dev/#/showcase/idealists
{"code":200,"data":[],"message":"success"}

**Comment by Ray-D-Song** [comment]
> 目录中设置了可在showcase中展示，但实际访问showcase页面没有看到文章，是空白的。比如这个网址：https://web-archive-9ta.pages.dev/#/showcase/idealists {"code":200,"data":[],"message":"success"}

橱窗地址是 /showcase/folder，所有设置为可展示的页面都会在这个目录里

**Comment by robustmaster** [comment]
原来是folder，我还以为要把folder替换成目录名字。另外，folder后还需要加 /，不然会跳到登录页。在 2024年11月11日，08:38，Ray-D-Song ***@***.***> 写道：﻿

目录中设置了可在showcase中展示，但实际访问showcase页面没有看到文章，是空白的。比如这个网址：https://web-archive-9ta.pages.dev/#/showcase/idealists {"code":200,"data":[],"message":"success"}

橱窗地址是 /showcase/folder，所有设置为可展示的页面都会在这个目录里

**Comment by Ray-D-Song** [comment]
> 原来是folder，我还以为要把folder替换成目录名字。另外，folder后还需要加 /，不然会跳到登录页。在 2024年11月11日，08:38，Ray-D-Song ***@***.***> 写道：﻿ 目录中设置了可在showcase中展示，但实际访问showcase页面没有看到文章，是空白的。比如这个网址：https://web-archive-9ta.pages.dev/#/showcase/idealists {"code":200,"data":[],"message":"success"} 橱窗地址是 /showcase/folder，所有设置为可展示的页面都会在这个目录里 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

抱歉我的文档可能有一些误导性，不过没有`/`跳转到登录页并不是预期中的行为，比如这是我的橱窗，你应该可以直接访问：
https://web-archive-egm.pages.dev/#/showcase/folder

**Comment by robustmaster** [comment]
不可以，访问提示输入密码，到了登录页。在 2024年11月11日，10:16，Ray-D-Song ***@***.***> 写道：﻿

原来是folder，我还以为要把folder替换成目录名字。另外，folder后还需要加 /，不然会跳到登录页。在 2024年11月11日，08:38，Ray-D-Song @.> 写道：﻿ 目录中设置了可在showcase中展示，但实际访问showcase页面没有看到文章，是空白的。比如这个网址：https://web-archive-9ta.pages.dev/#/showcase/idealists {"code":200,"data":[],"message":"success"} 橱窗地址是 /showcase/folder，所有设置为可展示的页面都会在这个目录里 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.>

抱歉我的文档可能有一些误导性，不过没有/跳转到登录页并不是预期中的行为，比如这是我的橱窗，你应该可以直接访问：
https://web-archive-egm.pages.dev/#/showcase/folder

**Comment by Ray-D-Song** [comment]
> 不可以，访问提示输入密码，到了登录页。在 2024年11月11日，10:16，Ray-D-Song ***@***.***> 写道：﻿ 原来是folder，我还以为要把folder替换成目录名字。另外，folder后还需要加 /，不然会跳到登录页。在 2024年11月11日，08:38，Ray-D-Song @.> 写道：﻿ 目录中设置了可在showcase中展示，但实际访问showcase页面没有看到文章，是空白的。比如这个网址：https://web-archive-9ta.pages.dev/#/showcase/idealists {"code":200,"data":[],"message":"success"} 橱窗地址是 /showcase/folder，所有设置为可展示的页面都会在这个目录里 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> 抱歉我的文档可能有一些误导性，不过没有/跳转到登录页并不是预期中的行为，比如这是我的橱窗，你应该可以直接访问： https://web-archive-egm.pages.dev/#/showcase/folder —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

啊，抱歉，这是多余的 tag 请求导致了 bug，可以麻烦你单独开一个 issue 吗

**Comment by ishowman** [comment]
> 太nb了，接收omnivore难民😊而且还能绕过知乎验证，爱了❤️❤️❤️❤️❤️
> 
> ### 一些小建议 大佬看看就行:)
> * 希望可以在通过浏览器插件archive的时候直接新建分类，现在在浏览器插件中只能选中已有分类。
> * 目前只能在页面存在且等待浏览器插件提示完成，才能成功Archive. 希望可以直接把链接粘贴到插件Archive / 单击Save Page后可以安全地关闭页面，后台Save
> * 希望浏览器插件支持粘贴一些剪切板内容或者是文本（text），因为有时是不需要archive整个页面的，只希望保存部分文本。
> * 希望加入高亮、导入导出等等同类软件（readeck, hoarder, obsidian web clipper, omnivore）功能。
> 
> ### 发现一个Light Theme小bug：
> archive Telegraph的一个[页面](https://telegra.ph/2024%E5%B9%B4%E5%A4%A7%E9%80%89%E7%9A%84%E4%B8%80%E4%BA%9B%E6%84%9F%E6%83%B3%E6%88%91%E5%9C%A82016%E5%92%8C20-11-06)时，iframe生成的预览对比度过低。 ![image](https://private-user-images.githubusercontent.com/103420806/384652248-89a7eaba-85f6-4679-931a-2ead0eeb67bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MTE3MjksIm5iZiI6MTczMTgxMTQyOSwicGF0aCI6Ii8xMDM0MjA4MDYvMzg0NjUyMjQ4LTg5YTdlYWJhLTg1ZjYtNDY3OS05MzFhLTJlYWQwZWViNjdiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QwMjQzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDc1OGYyZmIxMDk1NGEwNzJmYzk0NzgzZGVkNzgzODkzMjJjN2U3MDU4NzFmN2E0NDNiOTRlMGVjN2U2MGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WHERpUjfX-nqd3E_1Wc6WZOWh0i4EMRg9PdTXKj-J5g)

请问omnivore难民要如何迁移过来呢？  @Hyphen-H

**Comment by ishowman** [comment]
能增加下 contribute 描述如何本地开发项目吗. @Ray-D-Song

**Comment by banzhe** [comment]
> 能增加下 contribute 描述如何本地开发项目吗. @Ray-D-Song

`pnpm run dev:server`启动后端(这一步本地会自动创建d1数据库）
服务启动之后，命令行进入packages/server目录下，使用`npx wrangler d1 migrations apply web-archive --local`初始化数据库，之后需要重启一下server

`pnpm run dev:web`启动前端
`pnpm run dev:plugin`启动插件(dev下插件构建的输出位置在packages/plugin/extension下，浏览器直接加载这个文件夹就行了)

有空了我会补充个详细的

**Comment by ishowman** [comment]
> > 能增加下 contribute 描述如何本地开发项目吗. @Ray-D-Song
> 
> `pnpm run dev:server`启动后端(这一步本地会自动创建d1数据库） 服务启动之后，命令行进入packages/server目录下，使用`npx wrangler d1 migrations apply web-archive --local`初始化数据库，之后需要重启一下server
> 
> `pnpm run dev:web`启动前端 `pnpm run dev:plugin`启动插件(dev下插件构建的输出位置在packages/plugin/extension下，浏览器直接加载这个文件夹就行了)
> 
> 有空了我会补充个详细的

好的谢谢。本地环境只需要安装 node 就行是么？

**Comment by banzhe** [comment]
> > > 能增加下 contribute 描述如何本地开发项目吗. @Ray-D-Song
> > 
> > 
> > `pnpm run dev:server`启动后端(这一步本地会自动创建d1数据库） 服务启动之后，命令行进入packages/server目录下，使用`npx wrangler d1 migrations apply web-archive --local`初始化数据库，之后需要重启一下server
> > `pnpm run dev:web`启动前端 `pnpm run dev:plugin`启动插件(dev下插件构建的输出位置在packages/plugin/extension下，浏览器直接加载这个文件夹就行了)
> > 有空了我会补充个详细的
> 
> 好的谢谢。本地环境只需要安装 node 就行是么？

[pnpm](https://pnpm.io/installation#using-npm)也要先安装一下

**Comment by ishowman** [comment]
插件能不能顺便发布到 edge 浏览器呢

**Comment by banzhe** [comment]
> 插件能不能顺便发布到 edge 浏览器呢

这周我会顺便申请一下，不过edge不是也能装chrome插件商店的插件吗

**Comment by ishowman** [comment]
> > 插件能不能顺便发布到 edge 浏览器呢
> 
> 这周我会顺便申请一下，不过edge不是也能装chrome插件商店的插件吗

可以安装，但不能账号登录云同步自动安装

**Comment by banzhe** [comment]
> > > 插件能不能顺便发布到 edge 浏览器呢
> > 
> > 
> > 这周我会顺便申请一下，不过edge不是也能装chrome插件商店的插件吗
> 
> 可以安装，但不能账号登录云同步自动安装

edge插件的地址
https://microsoftedge.microsoft.com/addons/detail/webarchive/kdakdhbobdjddjapebmoekoomombcann

**Comment by yitong2333** [comment]
![Image](https://github.com/user-attachments/assets/6756960c-0aa4-4102-9bb4-17e742649413)
AI生成Tag需要配置么？如何配置？默认会报错

**Comment by banzhe** [comment]
> ![Image](https://github.com/user-attachments/assets/6756960c-0aa4-4102-9bb4-17e742649413) AI生成Tag需要配置么？如何配置？默认会报错

在网页端的设置里配置

![Image](https://github.com/user-attachments/assets/9d745f22-328c-442a-8024-b0badcaf1275)

**Comment by yitong2333** [comment]
> > ![Image](https://github.com/user-attachments/assets/6756960c-0aa4-4102-9bb4-17e742649413) AI生成Tag需要配置么？如何配置？默认会报错
> 
> 在网页端的设置里配置
> 
> ![Image](https://github.com/user-attachments/assets/9d745f22-328c-442a-8024-b0badcaf1275)

看来是我的版本太低了，我去升个版本

**Comment by ZhaoTim** [comment]
✘ [ERROR] Couldn't find a D1 DB with the name or binding 'web-archive' in your wrangler.toml file.

 请问为什么github action中报错如上信息？

**Comment by banzhe** [comment]
> ✘ [ERROR] Couldn't find a D1 DB with the name or binding 'web-archive' in your wrangler.toml file.
> 
> 请问为什么github action中报错如上信息？

具体在action中的哪一个步骤出了问题？Deoloy吗
正常会在Check and Create D1 Database中检测并创建数据库，然后在update wrangler.toml中把对应数据库的配置写道wrangler.toml里

**Comment by ZhaoTim** [comment]
> > ✘ [ERROR] Couldn't find a D1 DB with the name or binding 'web-archive' in your wrangler.toml file.
> > 请问为什么github action中报错如上信息？
> 
> 具体在action中的哪一个步骤出了问题？Deoloy吗 正常会在Check and Create D1 Database中检测并创建数据库，然后在update wrangler.toml中把对应数据库的配置写道wrangler.toml里

🙏🙏 我尝试重新deploy以后，就好了。很神奇，我什么都没动过。感谢这么好的项目！
