### ISSUE TITLE
保存的网站 logo 无法显示

### ISSUE THREAD

**Issue by nobodysclown** [Ray-D-Song/web-archive#39]
惠普官网的 logo 无法显示
![PixPin_2024-11-10_12-16-42](https://github.com/user-attachments/assets/96566431-52cb-4dbc-8fa5-cb5a919c55bf)

**Comment by Ray-D-Song** [comment]
HP 这个 logo 是用的伪元素+unicode图标字体，无法被内联到 html 中。
