### ISSUE TITLE
[功能请求] 有什么办法能在移动端设备上实现收藏网页吗？

### ISSUE THREAD

**Issue by FlechazoPh** [Ray-D-Song/web-archive#44]
例如iOS，手机上看公众号或者小红书的文章写收藏的需求也挺多的。

1. 是否能通过类似 快捷指令，发送API请求，附带剪切板网址链接，或者分享网页链接的方式实现？
2. 或者接入微信或者 TG 等机器人，通过分享网页链接的方式实现

**Comment by Ray-D-Song** [comment]
移动端在 roadmap 中，但是优先级不高，因为 ios 开发者账号需要付费，很不巧我的账号过期。

**Comment by FlechazoPh** [comment]
> 移动端在 roadmap 中，但是优先级不高，因为 ios 开发者账号需要付费，很不巧我的账号过期。

其实也暂时可以不开发APP，使用快捷指令发送网址api请求能否暂时实现呢？

**Comment by banzhe** [comment]
> > 移动端在 roadmap 中，但是优先级不高，因为 ios 开发者账号需要付费，很不巧我的账号过期。
> 
> 
> 
> 其实也暂时可以不开发APP，使用快捷指令发送网址api请求能否暂时实现呢？

这种方式没有办法抓取页面，存了也只能当成书签来用

**Comment by FlechazoPh** [comment]
> > > 移动端在 roadmap 中，但是优先级不高，因为 ios 开发者账号需要付费，很不巧我的账号过期。
> > 
> > 
> > 其实也暂时可以不开发APP，使用快捷指令发送网址api请求能否暂时实现呢？
> 
> 这种方式没有办法抓取页面，存了也只能当成书签来用

哦对，网页渲染抓取是在客户端进行的，要在服务端进行还得环境支持，还要过登录鉴权
