### ISSUE TITLE
【功能请求】期望能在 Save的时候就能设置是否展示在showacase里

### ISSUE THREAD

**Issue by FlechazoPh** [Ray-D-Song/web-archive#45]
![image](https://github.com/user-attachments/assets/4e89c1a2-d322-48be-b400-6a1140e3ff10)

现在每次都是去控制台设置是否展示在橱窗里

另外期望在插件页面和橱窗里能直接增加一个跳转到橱窗页面的跳转入口

![image](https://github.com/user-attachments/assets/b45844c9-016f-4a67-9506-a414a372b72d)

**Comment by Ray-D-Song** [comment]
会在 0.1.1 添加

**Comment by Ray-D-Song** [comment]
已完成
