### ISSUE TITLE
[问题] 正确安装，但是无法保存

### ISSUE THREAD

**Issue by bob-zebedy** [Ray-D-Song/web-archive#51]
https://github.com/user-attachments/assets/f1d8f010-52a2-41de-8482-460c5279204a

**Comment by banzhe** [comment]
插件设置按钮右边有一个历史任务列表按钮, 点击进去之后可以看到失败的任务, 移动到×号上时会显示失败时捕获的异常

**Comment by bob-zebedy** [comment]
> 插件设置按钮右边有一个历史任务列表按钮, 点击进去之后可以看到失败的任务, 移动到×号上时会显示失败时捕获的异常

![Google Chrome--20241118190609-0XImEuhw@2x](https://github.com/user-attachments/assets/39f3caf9-14cb-405e-ad01-a4c879f06730)

**Comment by banzhe** [comment]
已修复，这是main分支版本比release里的插件新导致的...
