### ISSUE TITLE
点击保存后，数据没出现在部署的网站

### ISSUE THREAD

**Issue by ishowman** [Ray-D-Song/web-archive#55]
之前是要过好几分钟后才能看到保存后的网页；现在是保存后也不会显示在网页中，不知道保存了没有

**Comment by Ray-D-Song** [comment]
- 贴一下使用的浏览器和需要保存的网页。
- 查看插件的保存列表，看一下状态。
- 如果几分钟后会在服务里出现，大概率是和page的网络不通畅。

**Comment by ishowman** [comment]
![image](https://github.com/user-attachments/assets/ecc42849-a220-438d-8dea-d02603800c76)
该问题出现在b 站，你可以测试一下 https://www.bilibili.com/video/BV1BS421X7dp/?vd_source=c6589deb50e4e0d0cc58933856c4e45c  @Ray-D-Song

**Comment by banzhe** [comment]
> ![image](https://private-user-images.githubusercontent.com/16897283/391214180-ecc42849-a220-438d-8dea-d02603800c76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NDU5NDMsIm5iZiI6MTczMjk0NTY0MywicGF0aCI6Ii8xNjg5NzI4My8zOTEyMTQxODAtZWNjNDI4NDktYTIyMC00MzhkLThkZWEtZDAyNjAzODAwYzc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDA1NDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NGJhZDEwODE3MTAzY2E1ZmU3N2MzOWVjMDE2ZGM1MmM4YzVhZjk5YTg0NzRkZWYwNzUwYTQ0YzQxODk4ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hQ_Hf4i-Hd-o1HEKdfNMtf7TtqKjTbVml3kuZGUd8WI) 该问题出现在b 站，你可以测试一下 https://www.bilibili.com/video/BV1BS421X7dp/?vd_source=c6589deb50e4e0d0cc58933856c4e45c @Ray-D-Song

移动到那个红色的错误图标上时会显示对应的错误信息
我测试的时候保存B站页面有概率失败，可能还是网络的问题，我会看一下能不能优化一下上传

**Comment by ishowman** [comment]
> > ![image](https://private-user-images.githubusercontent.com/16897283/391214180-ecc42849-a220-438d-8dea-d02603800c76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NDU5NDMsIm5iZiI6MTczMjk0NTY0MywicGF0aCI6Ii8xNjg5NzI4My8zOTEyMTQxODAtZWNjNDI4NDktYTIyMC00MzhkLThkZWEtZDAyNjAzODAwYzc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDA1NDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NGJhZDEwODE3MTAzY2E1ZmU3N2MzOWVjMDE2ZGM1MmM4YzVhZjk5YTg0NzRkZWYwNzUwYTQ0YzQxODk4ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hQ_Hf4i-Hd-o1HEKdfNMtf7TtqKjTbVml3kuZGUd8WI) 该问题出现在b 站，你可以测试一下 https://www.bilibili.com/video/BV1BS421X7dp/?vd_source=c6589deb50e4e0d0cc58933856c4e45c @Ray-D-Song
> 
> 移动到那个红色的错误图标上时会显示对应的错误信息 我测试的时候保存B站页面有概率失败，可能还是网络的问题，我会看一下能不能优化一下上传

显示 unexpected shutdown

**Comment by kiwiflydream** [comment]
我也遇到类似的问题，目前已解决。原因是我只升级了后端服务，没有更新插件，插件提示保存成功，但是其实后端没有保存。更新插件后成功。

**Comment by ishowman** [comment]
@Ray-D-Song 我的一直是最新的0.11版本插件。github 今天保存https://github.com/keephq/keep，出现抓取Scraping Page Data...后一直 loading，但好像并没有成功添加保存的任务，在save history里看不到记录

**Comment by banzhe** [comment]
> @Ray-D-Song 我的一直是最新的0.11版本插件。github 今天保存[https://github.com/keephq/keep，出现抓取Scraping](https://github.com/keephq/keep%EF%BC%8C%E5%87%BA%E7%8E%B0%E6%8A%93%E5%8F%96Scraping) Page Data...后一直 loading，但好像并没有成功添加保存的任务，在save history里看不到记录

我在0.1.2版本里对上传做了优化，但是只在chrome110+上生效，原先保存失败的原因应该是上传的请求超过30s时，插件的background service被浏览器自动停掉了

**Comment by ishowman** [comment]
> > @Ray-D-Song 我的一直是最新的0.11版本插件。github 今天保存[https://github.com/keephq/keep，出现抓取Scraping](https://github.com/keephq/keep%EF%BC%8C%E5%87%BA%E7%8E%B0%E6%8A%93%E5%8F%96Scraping) Page Data...后一直 loading，但好像并没有成功添加保存的任务，在save history里看不到记录
> 
> 我在0.1.2版本里对上传做了优化，但是只在chrome110+上生效，原先保存失败的原因应该是上传的请求超过30s时，插件的background service被浏览器自动停掉了

edge 浏览器内核相同，适用吗

**Comment by banzhe** [comment]
> > > @Ray-D-Song 我的一直是最新的0.11版本插件。github 今天保存[https://github.com/keephq/keep，出现抓取Scraping](https://github.com/keephq/keep%EF%BC%8C%E5%87%BA%E7%8E%B0%E6%8A%93%E5%8F%96Scraping) Page Data...后一直 loading，但好像并没有成功添加保存的任务，在save history里看不到记录
> > 
> > 
> > 我在0.1.2版本里对上传做了优化，但是只在chrome110+上生效，原先保存失败的原因应该是上传的请求超过30s时，插件的background service被浏览器自动停掉了
> 
> edge 浏览器内核相同，适用吗

可以
