### ISSUE TITLE
使用workers一键部署之后，第一次登录就需要输入密码吗？

### ISSUE THREAD

**Issue by xbpk3t** [Ray-D-Song/web-archive#56]
默认密码是什么呢？

另外，怎么自定义密码？

**Comment by xbpk3t** [comment]
<img width="1254" alt="image" src="https://github.com/user-attachments/assets/8b3cfe22-320b-4d4c-8381-5502f57f8a56">

**Comment by Ray-D-Song** [comment]
第一次输入密码其实是注册。
第二次输入就是用第一次的密码登陆。

**Comment by xbpk3t** [comment]
这就有点尴尬了，我现在确实没有这个密码了。可以初始化密码吗？是不是需要重新部署啊

**Comment by Ray-D-Song** [comment]
> 这就有点尴尬了，我现在确实没有这个密码了。可以初始化密码吗？是不是需要重新部署啊

没有初始化密码，如果不写SQL的话，直接在Cloudflare面板中删除web-archive的数据库是最快的方法。

**Comment by xbpk3t** [comment]
okk
