### ISSUE TITLE
【feature】是否有方法为网页生成PDF或者图片

### ISSUE THREAD

**Issue by FlechazoPh** [Ray-D-Song/web-archive#58]
是否有方法为网页生成PDF或者图片，不管是服务端生成，或者是加个按钮，客户端生成都可以，便于分享文章内容

**Comment by FlechazoPh** [comment]
类似功能：
HTML转PDF
https://chromewebstore.google.com/detail/html%E8%BD%ACpdf/ljbonnllckbdpfpjncfaoiakjjgjfmde?hl=zh-CN

网页到PDF转换器
https://chromewebstore.google.com/detail/%E7%BD%91%E9%A1%B5%E5%88%B0pdf%E8%BD%AC%E6%8D%A2%E5%99%A8/gpkildejogofhhobidokcjpolaikgldj?hl=zh-CN

HTML转PDF工具，将HTML网页转换为PDF文件。
https://www.ilovepdf.com/zh-cn/html-to-pdf

**Comment by banzhe** [comment]
可以先提供一个下载单个html页面的功能, 转换成PDF太过复杂不会考虑

**Comment by Ray-D-Song** [comment]
0.1.2已实现
