### ISSUE TITLE
希望能上架应用市场，FireFox 重启一次就得重新添加一次临时插件

### ISSUE THREAD

**Issue by Tsai002** [Ray-D-Song/web-archive#63]
被 FireFox 太搞心态了。

另外称赞一句，web-archive 非常好用，简直就是我心中的所想。不知道有没有可能独立部署，不一定非得依赖 CloudFlare。

**Comment by Ray-D-Song** [comment]
上架已经在提交了，要填的东西好多...
self-host 版本我也在开发中，主要是要实现 Cloudflare API 等价的垫片比较麻烦。
可能 self-host 要等明年才有。

**Comment by banzhe** [comment]
Firefox版商店地址: [web-archive](https://addons.mozilla.org/zh-CN/firefox/addon/web-archive-ray-banzhe/)
Chrome版还在审核
