### ISSUE TITLE
部署的时候出现报错

### ISSUE THREAD

**Issue by Lampon** [Ray-D-Song/web-archive#67]
错误信息
![image](https://github.com/user-attachments/assets/268a6349-2010-4ff5-b5ef-63136d632fce)
创建的token权限是这样的
![image](https://github.com/user-attachments/assets/3544a799-f9ef-429f-9c4f-4fe634a6939b)

是因为还有什么权限没有添加吗？

**Comment by Ray-D-Song** [comment]
是的，权限有问题，正确配置参考文档：
https://web-archive-docs.pages.dev/deploy.html

**Comment by Lampon** [comment]
为什么我的权限配置下拉选择，只有账户和区域，没有用户这个选项，这个是需要哪里操作的？
![image](https://github.com/user-attachments/assets/c86b7827-86c7-4276-adff-c038452b575b)

**Comment by Ray-D-Song** [comment]
用户应该不是必须的，你只需要选择 `编辑 Cloudflare Workers` 模版，再手动添加 `D1 编辑` 权限就行。

**Comment by Lampon** [comment]
还是不行，我是选择了 Cloudflare Workers 模版，然后手动添加了D1 编辑，还是会报上面的错误，应该真的和这个用户权限有关心，不知道这个用户权限要怎么才能有
![image](https://github.com/user-attachments/assets/c54d5d12-00e2-464b-9350-78a6df924c62)

**Comment by banzhe** [comment]
https://dash.cloudflare.com/profile/api-tokens
试一下在这个面板里创建token呢, 账户API令牌里新建是没有用户选项的, 个人资料里的API令牌才有用户选项

**Comment by Lampon** [comment]
> https://dash.cloudflare.com/profile/api-tokens 试一下在这个面板里创建token呢, 账户API令牌里新建是没有用户选项的, 个人资料里的API令牌才有用户选项

感谢，是这个问题，解决了
