### ISSUE TITLE
AI标签添加失败问题

### ISSUE THREAD

**Issue by gonghailink** [Ray-D-Song/web-archive#69]
![Web Archive](https://github.com/user-attachments/assets/aadc5f55-9dac-4242-bde9-d1463f39b8d5)
如图所示，在添加AI标签识别的时候出现错误不知道怎么解决，希望大佬说明一下，我还没有添加变量，是不是需要添加变量？还是部署的时候哪里出现问题了？

**Comment by banzhe** [comment]
你说的变量是指什么，我这里用新账号试了一下可以保存，报这个错可能是请求配置接口404了，你能把控制台里的错误发出来吗

**Comment by gonghailink** [comment]
> 你说的变量是指什么，我这里用新账号试了一下可以保存，报这个错可能是请求配置接口404了，你能把控制台里的错误发出来吗

我是部署到cf的里面的，不是在本地部署，全程都是cloudflare和github设置和自动部署，没有用ssh，刚刚在github的Actions部署里找了两遍也没找到问题所在

**Comment by gonghailink** [comment]
> 你说的变量是指什么，我这里用新账号试了一下可以保存，报这个错可能是请求配置接口404了，你能把控制台里的错误发出来吗

对了，刚才忘记跟你说，web-archive登录后都会出现Network error报错，但浏览器插件登录和同步收藏都没问题，

**Comment by gonghailink** [comment]
> 你说的变量是指什么，我这里用新账号试了一下可以保存，报这个错可能是请求配置接口404了，你能把控制台里的错误发出

> 你说的变量是指什么，我这里用新账号试了一下可以保存，报这个错可能是请求配置接口404了，你能把控制台里的错误发出来吗

原因找到了，用workes自带的域名登录没有这两个报错，用托管在cf绑定的域名登录会报这两个错。

**Comment by Ray-D-Song** [comment]
> > 你说的变量是指什么，我这里用新账号试了一下可以保存，报这个错可能是请求配置接口404了，你能把控制台里的错误发出
> 
> > 你说的变量是指什么，我这里用新账号试了一下可以保存，报这个错可能是请求配置接口404了，你能把控制台里的错误发出来吗
> 
> 原因找到了，用workes自带的域名登录没有这两个报错，用托管在cf绑定的域名登录会报这两个错。

我刚刚绑定域名测试了一下，没有复现。  
你可以检查一下 Cloudflare 的 DNS 设置吗？

Cloudflare worker 有两个版本，一个是类似 https://web-archive-egm.pages.dev 的正式版。
还有一个是类似 https://be91a88f.web-archive-egm.pages.dev 的临时实例版本。
确保要绑定到正式版上。

**Comment by gonghailink** [comment]
大哥，你这么说我也懵了，我是在Cloudflare的pages部署的，不是在Workers部署，是按照你这个链接的教程配置https://web-archive-docs.pages.dev/deploy 然后是项目自动拉取部署的
刚刚检查了一遍DNS，所有pages部署的项目都是直接在部署项目里的自定义域添加域名都可以正常使用，实在是不知道你还有一个临时实例版本。

**Comment by gonghailink** [comment]
> > > 你说的变量是指什么，我这里用新账号试了一下可以保存，报这个错可能是请求配置接口404了，你能把控制台里的错误发出来吗
> > 
> > 
> > 原因找到了，用workes自带的域名登录没有这两个报错，用托管在cf绑定的域名登录会报这两个错。
> 
> 我刚刚绑定域名测试了一下，没有复现。 你可以检查一下 Cloudflare 的 DNS 设置吗？
> 
> Cloudflare worker 有两个版本，一个是类似 https://web-archive-egm.pages.dev 的正式版。 还有一个是类似 https://be91a88f.web-archive-egm.pages.dev 的临时实例版本。 确保要绑定到正式版上。

大哥，你这么说我也懵了，我是在Cloudflare的pages部署的，不是在Workers部署，是按照你这个链接的教程配置https://web-archive-docs.pages.dev/deploy 然后项目是pages自动拉取部署的
刚刚检查了一遍DNS，所有pages部署的项目都是直接在部署项目里的自定义域添加域名都可以正常使用，实在是不知道你还有一个临时实例版本。

**Comment by gonghailink** [comment]
> > > 你说的变量是指什么，我这里用新账号试了一下可以保存，报这个错可能是请求配置接口404了，你能把控制台里的错误发出
> > 
> > 
> > > 你说的变量是指什么，我这里用新账号试了一下可以保存，报这个错可能是请求配置接口404了，你能把控制台里的错误发出来吗
> > 
> > 
> > 原因找到了，用workes自带的域名登录没有这两个报错，用托管在cf绑定的域名登录会报这两个错。
> 
> 我刚刚绑定域名测试了一下，没有复现。 你可以检查一下 Cloudflare 的 DNS 设置吗？
> 
> Cloudflare worker 有两个版本，一个是类似 https://web-archive-egm.pages.dev 的正式版。 还有一个是类似 https://be91a88f.web-archive-egm.pages.dev 的临时实例版本。 确保要绑定到正式版上。

检查过DNS 是绑定到正式版，在该项目添加自定义域名的位置添加的。

**Comment by gonghailink** [comment]
> > > 你说的变量是指什么，我这里用新账号试了一下可以保存，报这个错误可能是请求配置接口404了，你可以把控制台里的错误发出来
> > 
> > 
> > > 你说的变量是指什么，我这里用新账号试了一下可以保存，报这个错误可能是请求配置接口404了，你可以把控制台里的错误发出来吗？
> > 
> > 
> > 原因找到了，用workes自带的域名登录没有这两个错误，用托管在cf绑定的域名登录会报这两个错误。
> 
> 我刚刚绑定了域名测试视图，没有复现。 您可以检查一下 Cloudflare 的 DNS 设置吗？
> 
> Cloudflare Worker 有两个版本，一个是类似https://web-archive-egm.pages.dev的正式版本。 还有一个是类似https://be91a88f.web-archive-egm.pages.dev的临时实例版本。 确保要绑定到正式版本上。

已解决，今天突然想起来防火墙，刚查看防火墙是防火墙规则拦截了
