### ISSUE TITLE
删除条目，但是仍占用R2存储空间

### ISSUE THREAD

**Issue by hiing** [Ray-D-Song/web-archive#70]
R2应该有读写编辑功能，希望实现在删除按钮之后，R2同步删除

**Comment by Ray-D-Song** [comment]
删除之后会进入垃圾箱，也就是左下角的 trash ，清倒废纸篓后 R2 会同步删除。

**Comment by hiing** [comment]
OK，是没发现有个单独的trash功能，感谢
